name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: backend
        run: mvn --batch-mode clean install  
        env:
          GITHUB_ACTOR: ${{ secrets.CR_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.CR_TOKEN }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker build
        working-directory: backend
        run: |
          VERSION=0.1
          DOCKER_IMAGE_PREFIX_LOWER=$(echo $DOCKER_IMAGE_PREFIX | awk '{print tolower($0)}')
          mvn dockerfile:build dockerfile:push -Ddocker.image.tag=$VERSION -Ddocker.image.prefix=$DOCKER_IMAGE_PREFIX_LOWER
        env:
          DOCKER_IMAGE_PREFIX: ${{ env.REGISTRY_NAME }}/${{ github.repository }}
          GITHUB_ACTOR: ${{ secrets.CR_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.CR_TOKEN }}

